config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'inventory/index'
  root 'inventory#index'
  resources :inventories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:part_number, :description, :quantity)
    end
end

app/controllers/inventory_controller.rb
class InventoryController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/views/inventories/_form.html.erb
<div class="container">
  <%= form_with(model: inventory, local: true) do |form| %>
    <% if inventory.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

        <ul>
        <% inventory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :part_number %>
      <%= form.text_field :part_number, id: :inventory_part_number %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description, id: :inventory_description %>
    </div>

    <div class="field">
      <%= form.label :quantity %>
      <%= form.number_field :quantity, id: :inventory_quantity %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Inventories</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Part number</th>
        <th>Description</th>
        <th>Quantity</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @inventories.each do |inventory| %>
        <tr>
          <td><%= inventory.part_number %></td>
          <td><%= inventory.description %></td>
          <td><%= inventory.quantity %></td>
          <td><%= link_to 'Show', inventory %></td>
          <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
          <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Inventory', new_inventory_path %>
</div>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part number:</strong>
  <%= @inventory.part_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @inventory.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @inventory.quantity %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/inventory/index.html.erb
<div class="container">
	<div class="jumbotron">
	  <h1 class="display-3">Welcome to Louver Inventory!</h1>
	  <p class="lead">Here is where you can control the Louver Inventory</p>
	  <hr class="my-4">
	  <p>Click on Inventory to get started</p>
	  <p class="lead">
	    <!-- <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
      <% if user_signed_in? %>
        <%= link_to 'Inventory', inventories_path, :class => "btn btn-primary" %>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path, :class => "btn btn-primary" %>
        <%= link_to 'Sign up', new_user_registration_path, :class => "btn btn-primary" %>
      <% end %>
	  </p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LouverInventory</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
  	<div class="container">
  		 <% if user_signed_in? %>
  		   <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  		 <% end %>  
  	   <%= link_to '<i class="fa fa-home fa-3x pull-right" aria-hidden="true"></i>'.html_safe, root_path %>
  	</div>  
  	<div class="container">
      <%flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
  	</div>
    <%= yield %>
  </body>
</html>